version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go_api
    networks:
      - my_network

  go_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge